name: map_picker_india
description: "A Flutter package that simplifies location selection on maps, regardless of device type."
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  geolocator: ^11.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0